# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.runs/synth_1/.Xil/Vivado-17840-DESKTOP-T2K4A01/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter perfStrategy 1
    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a35tfgg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog {
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/ALU.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Brch_M.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Cache_L1.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Control_Unit.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Instruction_Memory.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Program_counter.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Uart_programer.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/Vizual_32b.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/freqctrl.v}
      {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.srcs/sources_1/new/GPPU.v}
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList {{C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.runs/synth_1/.Xil/Vivado-17840-DESKTOP-T2K4A01/realtime/GPPU_synth.xdc}}
    rt::sdcChecksum
    set rt::top GPPU
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter combineLutsPostRebuildHierarchy false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter maxClockBufferCount 7
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter inferFsm true
    rt::set_parameter encodeFsm one_hot
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops false
    rt::set_parameter earlyMaximalSharing false
    rt::set_parameter inferLoadableAdd false
    rt::set_parameter inferCounter false
    rt::set_parameter shareDatapathInElaborate false
    rt::set_parameter srlDepthThreshold 5
    rt::set_parameter rstSrlDepthThreshold 6
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Ciudad Maderas/Documents/GCPU_implementation-/ALU/ALU.runs/synth_1/.Xil/Vivado-17840-DESKTOP-T2K4A01/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    rt::set_parameter incrementalOnCache ""
    rt::set_parameter doIncremental false
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
